#include "images.h"

const ext_img_desc_t images[25] = {
    { "battery", &img_battery },
    { "battlevel", &img_battlevel },
    { "play", &img_play },
    { "pause", &img_pause },
    { "incoming", &img_incoming },
    { "outgoing", &img_outgoing },
    { "ended", &img_ended },
    { "arrow", &img_arrow },
    { "01_straight", &img_01_straight },
    { "02_slight_left", &img_02_slight_left },
    { "03_left", &img_03_left },
    { "04_sharp_left", &img_04_sharp_left },
    { "05_slight_right", &img_05_slight_right },
    { "06_right", &img_06_right },
    { "07_sharp_right", &img_07_sharp_right },
    { "08_u_turn_left", &img_08_u_turn_left },
    { "09_u_turn_right", &img_09_u_turn_right },
    { "10_roundabout_right", &img_10_roundabout_right },
    { "11_roundabout_upper_right", &img_11_roundabout_upper_right },
    { "12_roundabout_straight", &img_12_roundabout_straight },
    { "13_roundabout_upper_left", &img_13_roundabout_upper_left },
    { "14_roundabout_left", &img_14_roundabout_left },
    { "15_roundabout_lower_left", &img_15_roundabout_lower_left },
    { "16_roundabout_lower_right", &img_16_roundabout_lower_right },
    { "17_roundabout_u_turn", &img_17_roundabout_u_turn },
};